PETOI_COMMANDS: dict[str, str] = {
    # ── GAITS ────────────────────────────────────────────────────────────────
    "bdF": "Bound forward — fast bounding gait",
    "bk": "Walk backward",
    "bkF": "Walk backward (forward-facing variant)",
    "bkL": "Walk backward turning left",
    "bkR": "Walk backward turning right (mirrored from bkL)",
    "carpetF": "Walk forward on carpet — adapted gait for soft surfaces",
    "carpetL": "Walk left on carpet — adapted gait for soft surfaces",
    "carpetR": "Walk right on carpet — adapted gait for soft surfaces (mirrored from carpetL)",
    "crF": "Crawl forward — slow, low-profile gait",
    "crL": "Crawl left",
    "crR": "Crawl right (mirrored from crL)",
    "gpF": "Gallop forward",
    "gpL": "Gallop left",
    "gpR": "Gallop right (mirrored from gpL)",
    "hlw": "Halloween walk — seasonal themed gait",
    "jpF": "Jump/hop forward — hopping gait",
    "lftF": "Lift walk forward — high-stepping gait",
    "lftL": "Lift walk left — high-stepping gait",
    "lftR": "Lift walk right — high-stepping gait (mirrored from lftL)",
    "phF": "Push forward — pushing gait (head down, driving forward)",
    "phL": "Push left",
    "phR": "Push right (mirrored from phL)",
    "trF": "Trot forward — medium-speed diagonal gait",
    "trL": "Trot left",
    "trR": "Trot right (mirrored from trL)",
    "vtF": "Vertical step forward — stepping in place / slow march",
    "vtL": "Vertical step left",
    "vtR": "Vertical step right (mirrored from vtL)",
    "wkF": "Walk forward — standard walking gait",
    "wkL": "Walk left",
    "wkR": "Walk right (mirrored from wkL)",
    # ── POSTURES ─────────────────────────────────────────────────────────────
    "balance": "Standing balance — default neutral standing posture",
    "buttUp": "Butt up — rear raised, front lowered (play bow)",
    "calib": "Calibration posture — all joints at calibration angles",
    "dropped": "Dropped response — posture when robot detects it fell",
    "lifted": "Lifted response — posture when robot detects it's picked up",
    "lnd": "Landing posture — stabilisation after a jump/flip",
    "rest": "Rest — deactivate all servos (go limp)",
    "sit": "Sit — sitting posture",
    "str": "Stretch — stretching posture (like a dog waking up)",
    "up": "Stand up — rise to standing position",
    "zero": "Zero position — all servos to 0° reference angles",
    # ── TRICKS / BEHAVIOURS ──────────────────────────────────────────────────
    "ang": "Angry — angry reaction posture/animation",
    "bf": "Backflip",
    "bx": "Boxing — boxing punching motion",
    "chr": "Cheer — cheerful celebration animation",
    "ck": "Check — look around / inspect surroundings",
    "clap": "Clap — front paws clapping motion",
    "cmh": "Come here — beckoning / approach gesture",
    "dg": "Dig — digging motion with front paws",
    "dropRec": "Drop recovery — recover from a fallen/dropped state",
    "ff": "Front flip",
    "fiv": "High five — raise paw for a high five",
    "flip": "Flip — body flip",
    "gdb": "Good boy — happy/rewarded reaction animation",
    "hds": "Handstand — front legs up, balancing on rear legs",
    "hg": "Hug — hugging motion with front legs",
    "hi": "Greeting — wave / say hello with front paw",
    "hsk": "Handshake — extend paw for a handshake",
    "hu": "Hurdle — jump over obstacle motion",
    "hunt": "Hunt — stalking/hunting animation",
    "jmp": "Jump — jump in place",
    "kc": "Kick — kick with leg",
    "knock": "Knock — knocking motion with front paw",
    "launch": "Launch — powerful upward jump",
    "lucky": "Lucky — lucky cat paw wave (maneki-neko style)",
    "mw": "Moonwalk — moonwalk dance move",
    "nd": "Nod — head nodding motion",
    "pd": "Play dead — roll over and lie still",
    "pee": "Pee — lift leg (marking territory)",
    "pu": "Push-up — push-up exercise",
    "pu1": "Push-up single-handed — one-paw push-up",
    "rc": "Recover — self-right from overturned position",
    "rl": "Roll — roll over sideways",
    "scrh": "Scratch — scratch self with hind leg",
    "showOff": "Show off — showy trick sequence",
    "snf": "Sniff — sniffing the ground motion",
    "tbl": "Table — flatten back to become a table surface",
    "ts": "Test — test/diagnostic movement sequence",
    "wh": "Wiggle head — shake/wiggle head side to side",
    "zz": "Sleep — sleeping animation",
}
